"""blog models updated 

Revision ID: 1682a0e27c25
Revises: e81e0c5d8021
Create Date: 2021-11-23 20:54:37.166219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1682a0e27c25'
down_revision = 'e81e0c5d8021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blogs', ['title'])
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'blogs', type_='unique')
    # ### end Alembic commands ###
