"""All Model created

Revision ID: bdfa1e25977f
Revises: b3d0e76571bb
Create Date: 2021-11-22 18:55:22.384568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfa1e25977f'
down_revision = 'b3d0e76571bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('loc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'loc')
    # ### end Alembic commands ###
